config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'places#index'
  
  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
#because a comment belongs specifically to one user and one place
#comments point to user and place, other tables in the db
  belongs_to :user
  belongs_to :place
  #an active record callback
  after_create :send_comment_email

    RATINGS = {
    'one star': '1_star',
    'two stars': '2_stars',
    'three stars': '3_stars',
    'four stars': '4_stars',
    'five stars': '5_stars'
  }
#Calls this method for all comments
  def humanized_rating
    RATINGS.invert[self.rating]
  end

#Use the after_create callback to send an email about comment after user comments
  def send_comment_email
    #Self uses the current comment this method is called on
    NotificationMailer.comment_added(self).deliver_now
  end
end

app/models/photo.rb
class Photo < ApplicationRecord

  belongs_to :place
  mount_uploader :picture, PictureUploader

end

app/models/place.rb
class Place < ApplicationRecord
  #because a place belongs to a specific user and a place has many comments
  belongs_to :user
  #place has many comments
  has_many :comments
  #place has many photos
  has_many :photos
  
  geocoded_by :address
  after_validation :geocode
  #Uses active_record validations to mean that each place has to have a name, address, and description
  validates :name, length: { minimum: 3 }, presence: true
  validates :address, presence: true
  validates :description, presence: true


  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
#because one user will have many comments and places they add in the db
  has_many :places
  has_many :comments
  #has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #Requires user to be logged in
  before_action :authenticate_user!

  def create
    #Pulls place_id out of the URL
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private
  #pull data out of comment form
  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    #Sets params from has_many: photos in place.rb model
    @place.photos.create(photo_params)
    redirect_to place_path(@place)
  end


  private 

  def photo_params
    params.require(:photo).permit(:picture, :caption)
  end
end

app/controllers/places_controller.rb
  class PlacesController < ApplicationController
    #With before_action only a logged in user can access the new, create etc methods
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
        #Allows a before filter which only lets logged in users
        #access 'new' and 'create'. Users not logged in will be directed
        #to the login in page when clicking on 'new place'
      before_action :authenticate_user!, only: [:new, :create]
  def index
    @places = Place.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @place = Place.new
  end
  #Runs when the create button pressed on the form
  def create
      #Place.create(place_params)
      #Creates a place connected with the user. Knows this bc of has_many :places
      #in the user.rb file and sets it to @place
      @place = current_user.places.create(place_params)
      #if place valid, go to root_path, else go to the new form again and throw validation error
      if @place.valid?
        redirect_to root_path
      else
        render :new, status: :unprocessable_entity
      end
  end

def show
  #apparently loads the Place id into the variable @place to be
  #passed to the show.html.erb view file so the place name a user
  #clicks on will show up on the page
  @place = Place.find(params[:id])
  @comment = Comment.new
  #Add to make photo variable valid in show.html.erb
  @photo = Photo.new
end

def edit
  @place = Place.find(params[:id])
  #Only the current user that's signed in can access and edit their places
  if @place.user != current_user
    return render text: 'Not Allowed', status: :forbidden
  end
end

def update
  @place = Place.find(params[:id])
  #Only the current user that's signed in can access and update their places, returns 'not allowed' error
  if @place.user != current_user
    return render text: 'Not Allowed', status: :forbidden
  end

  @place.update_attributes(place_params)
  #if place valid, go to root_path, else go to the edit form again and throw validation error
  if @place.valid?
    redirect_to root_path
  else
    render :edit, status: :unprocessable_entity
  end
end
#def destroy will trigger destroy in show.html.erb
def destroy
  #finds the :id of the place 
  @place = Place.find(params[:id])
  #Display error message if user tries to destroy place they haven't created
  if @place.user != current_user
    return render text: 'Not Allowed', status: :forbidden
  end
  #destroys the found place
  @place.destroy
  #this directs user back to root_path
  redirect_to root_path
end

    private
#Says that user f.input created in new.html.erb is permitted and required  
  def place_params
    params.require(:place).permit(:name, :description, :address)

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#takes the id from the URL. looks up user in database and puts value in user variable
  def show
    @user = User.find(params[:id])
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#"><!--Nomster--></a>
      <%= link_to 'Nomster', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <!--<li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>-->
            
          <li class="nav-item">
            <!--<a class="nav-link" href="#">Link</a>-->
            <%= link_to new_place_path, class: 'nav-link' do %>
            <i class="fa fa-plus-circle"></i>
            New Place
            <% end %>
          </li>

          <!--<li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>-->
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
              <li class="nav-item">
                <!--links to user#show page-->
                <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <!--If user signed in then show a link to sign out on the nav-bar-->
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <!--If user not signed in,then show a link to sign in and another link to sign up-->
                <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
              </li>
            <% end %>

        <!--<form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>-->
      </div>
    </nav>
    <!--Use of bootstrap button classes for user alerts set by Devise gem-->
    <!--if notice.present doesn't display notice unless it's triggered-->
    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Your Place Here</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
     <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/index.html.erb
<!--Carousel for photos-->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <!--Can add additional index 3 etc to add more carousel items-->
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag 'slider1.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>Find the best sushi places</h3>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider2.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>Looking for sushi?</h3>
      </div>
    </div>
     <div class="carousel-item">
      <%= image_tag 'slider3.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>More tasty sushi</h3>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<% @places.each do |place| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <i><%= place.address %></i><br />
    <p><%= place.description %></p><br />

    <% if place.user.present? %>
      <small><%= place.user.email %></small>
    <% end %>
  </div>

  <% if place.comments.present? %>
    <div class="col-12 offset-1">
      <blockquote>
        <% if place.comments.last.humanized_rating.present? %>
          <b><%= place.comments.last.humanized_rating %></b> -
        <% end %>
        <%= place.comments.last.message %>
        <small><%= place.comments.last.user.email %></small>
      </blockquote>
    </div>
  <% end %>
<% end %>

<%= will_paginate @places %>
 

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
     <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>


app/views/places/show.html.erb
<div class="booyah-box col-10 offset-1">
  <h1><%= @place.name %></h1>
  <i><%= @place.address %></i>
  <br/><br/>
  <p><%= @place.description %></p>

<!--Displays image on page from carrierwave gem, otherwise image isn't shown-->
  <% @place.photos.each do |photo| %>
    <%= image_tag photo.picture %>
    <%= photo.caption %>
  <% end %>


<!--Not sure why I still have the style tags here, they probably need to be removed-->
<style>
   
</style>
  
  </head>
  <body>
  <div id="map"></div>

<% if @place.latitude.present? && @place.longitude.present? %>
  <script>
    function initMap() {
      var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 12,
        center: myLatLng
      });
      var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Hello World!'
      });
    }
  </script>

  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyApVVPW8cSuNDFJtqCLBe2FkFjtzj6d-3E&callback=initMap">
  </script>

  <div id="map"></div>
<% end %>

<br />

  <div class="button-float-right">
    <!--if user is the current user then they can only see the places that they've added-->
    <% if current_user && current_user == @place.user %>
    <!--Lets user edit place, only shows edit button to user logged in-->
      <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
    <!--Lets user delete place and only shows destory button once user is logged in, due to if statement abov-->
      <%= link_to 'Destroy', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>
<!--make sure to add clear class in master.scss for clear to work, it resets the 'float-right' from above-->

<div class="clear"></div>

<!-- Photo Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a photo</h4>
      </div>
      <div class="modal-body">
        <!--booyah-box .css template from master.scss-->
        <div class="booyah-box col-12">
          <h1>Add a photo</h1>
          <%= simple_form_for @photo, url:  place_photos_path(@place) do |f| %>
            <%= f.input :picture %>
            <%= f.input :caption %>
            <%= f.submit "Submit a photo", class: 'btn btn-primary' %>  
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<div class="col-10 offset-1"</div>
  <!--Make sure data-target and id are unique to each modal i.e. mymodal and mymodal1
    otherwise the code will direct it to whatever form is in 'mymodal'-->
  <!--Code for modal-->
  <!-- Button trigger modal (Modal code listed above)-->
  <button type="button" class="btn btn-primary btn-lg button-float-right" data-toggle="modal" data-target="#myModal">
    Add a photo
  </button>
</div>
<!--Photo modal end-->

<div class="clear"</div>

<!-- Comment Modal -->
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
      </div>
      <div class="modal-body">
        <!--Uses the simple_form gem, the url:'#' will direct to nothing but make the code work if you haven't found
        the path yet' is where the comment form should direct to-->
        <%= simple_form_for @comment, url:  place_comments_path(@place) do |f| %>
          <%= f.input :message %>
          <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
          <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>


<div class="col-10 offset-1"</div>
  <!--<h1 class="float-left">Comments</h1> I don't need this text here-->
  <!--Code for modal-->
  <!-- Button trigger modal (Modal code listed above)-->
  <button type="button" class="btn btn-primary btn-lg button- float-right" data-toggle="modal" data-target="#myModal1">
    Add a comment
  </button>
</div>
<!--Comment modal end-->

<!--Make sure to wrap col-12, col-sm-6 in a div class="row" for them to work-->
<div class="row">
<% @place.comments.each do |comment| %>
  <div class="col-12 col-sm-6">
    <blockquote>
      <!--Calls humanized_rating method set in comment.rb model-->
      <% if comment.humanized_rating.present? %>
        <b><%= comment.humanized_rating %></b> -
      <% end %>
      <%= comment.message %>
      <small><%= comment.user.email %></small>
    </blockquote>
  </div>
<% end %>




app/views/users/show.html.erb
<div class="booyah-box">
  <div class="row">
    <div class="col-4">
  <%= image_tag 'user.png' %>
    </div>
    <div class="col-8">
      <!--Adds user email-->
      <h1><%= @user.email %></h1>
      <!--Adds the date user joined site-->
      <h3>Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
      <h4><%= @user.comments.count %> total comments</h4>
      <h4><%= @user.comments.where(rating: '5_stars').count %> total 5 star reviews</h4>
    </div>
  </div>

  <div class="clear"></div>
</div>

<!--Adds comments-->
<h1 class="text-center">My Comments</h1>
<div class="row">
<% @user.comments.each do |comment| %>
  <div class="col-12 col-sm-6">
    <br /><br />
    <h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h2>
    <br /><br />
    <blockquote>
      <% if comment.humanized_rating.present? %>
        <b><%= comment.humanized_rating %></b> -
      <% end %>
      <%= comment.message %>
      <small><%= comment.user.email %></small>
    </blockquote>
  </div>
<% end %>
</div>

<div class="clear"></div>
<br /><br />
<h2 class="text-center">My Places</h2>
<br /><br />
<% @user.places.each do |place| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <i><%= place.address %></i><br />
    <p><%= place.description %></p><br />

    <% if place.user.present? %>
      <small><%= place.user.email %></small>
    <% end %>

    <% if place.comments.present? %>
      <div class="col-12">
        <blockquote>
          <% if place.comments.last.humanized_rating.present? %>
            <b><%= place.comments.last.humanized_rating %></b> -
          <% end %>
          <%= place.comments.last.message %>
          <small><%= place.comments.last.user.email %></small>
        </blockquote>
      </div>
    <% end %>
  </div>
<% end %>